### ISSUE TITLE
Avast reports virus: IDP.Generic

### ISSUE THREAD

**Issue by el3um4s** [armandoalonso/c3IDE#34] opened 2019-05-16 08:37 UTC
![image](https://user-images.githubusercontent.com/23579630/57838870-d528e300-77c5-11e9-9bf3-833f9add7a5a.png)

> Threat blocked
> We've blocked the threat **c3IDE.exe** from harming your computer
> Threat name: **IDP.Generic**
> Process: ...\c3IDE.exe
> Detected by: Behavior Shield

**Comment by armandoalonso** [comment] 2019-05-16 09:32
I have gone ahead and reported it to avast as a false positive. I have been using McAfee and it has not triggered. I will wait to hear back from avast.

**Comment by armandoalonso** [comment] 2019-05-16 09:35
what were you doing when it triggered the warning? Behavior Shield seems to be a monitoring process that triggers on file behavior that mimic malware. i have installed avast and am trying to to reproduce the issue? but it does not trigger? maybe the trigger was based on an action the application took.

**Comment by el3um4s** [comment] 2019-05-16 10:17
I just launched c3ide. The past few days he didn't report anything to me.

According to [VirusTotal](https://www.virustotal.com/gui/file/1d572e59e3470d1db7e93e9e407ef10e9de47f4a3e16d89cc81cbe0b4d6b3004/detection) there are no malware

![image](https://user-images.githubusercontent.com/23579630/57846430-76b73100-77d4-11e9-9ddf-0fa4718a0d83.png)

**Comment by armandoalonso** [comment] 2019-05-20 17:17
Got a response from avast 

![image](https://user-images.githubusercontent.com/7579560/58039728-9feffe00-7b01-11e9-9952-a142de2a5947.png)

closing this issue as it seems to be resovled

**Closed** 2019-05-20 17:18 UTC
Labels: question
